---

- name: verificar variables cargadas
  debug:
    var: sites_config_install

- import_tasks:  systemconfig.yml
  tags:
    - inst-systemconfig
    - lamp-install-wp

- import_tasks: php.yml 
  tags:
    - inst-php
    - lamp-install-wp

- import_tasks: apache2server.yml
  tags:
    - inst-apache
    - lamp-install-wp

- import_tasks: mysql.yml
  tags:
    - inst-mysql
    - lamp-install-wp

- import_tasks: wp-cli.yml
  tags:
    - inst-wp-cli
    - lamp-install-wp

- import_tasks: force-ssl-rproxy.yml
  tags:
    - lamp-install-wp
    - force-ssl

...
