---
# Instalacion de repositorios.

- name: Descargamos wp-cli para administrar WP
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    owner: "{{ adminwpcli }}"
    group: "www-data"
    mode: '0750'

- name: Instalar wordpress y crea la configuración inicial desde wp-cli
  ansible.builtin.shell:
    cmd: "cd /var/www/{{ item.value.http_host }} && wp --allow-root core install --url={{ item.value.http_fqdn }} --title={{ item.value.http_host }} --admin_user={{ item.value.wp_admin_user }} --admin_password={{ item.value.wp_admin_password }} --admin_email={{ item.value.wp_admin_email }}"
  become: yes
  loop: "{{ sites_config_install|dict2items }}"

- name: Instalar Plugins de WordPress
  ansible.builtin.shell:
    cmd: "cd /var/www/{{ item.0.value.http_host }} && wp --allow-root plugin install {{ item.1 }} --activate"
  become: yes
  loop: "{{ lookup('cartesian', sites_config_install|dict2items, plugin_list) }}"
  loop_control:
    loop_var: item

- name: Change the owner an permisions on New Plugins
  ansible.builtin.file:
    dest: "/var/www/{{ item.value.http_host }}/wp-content"
    state: directory
    recurse: true
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    #Set directories to 755 and files to 644
    mode: u=rwX,g=rX,o=rX
  loop: "{{ sites_config_install|dict2items }}"